const data = [
  {
    id: 1,
    first_name: "Foundation",
    last_name: "Davomiylik: 6 oy ",
    email: "Darslar soni: 24 ta",
    name: "Sulaymon Ne'matov",
    img: "../../Assets/img/sulaymon.png",
  },
  {
    id: 2,
    first_name: "Foundation",
    last_name: "Davomiylik: 6 oy ",
    email: "Darslar soni: 16 ta",
    name: "Husan Musayev",
    img: "",
  },
  {
    id: 3,
    first_name: "Web dasturlash",
    last_name: "Davomiylik: 6 oy ",
    email: "Darslar soni: 12 ta",
    name: "Muhammad Yunus",
    img: "",
  },
  {
    id: 4,
    first_name: "Backend",
    last_name: "Davomiylik: 6 oy ",
    email: "Darslar soni: 14 ta",
    name: "Muhammad Yunus",
    img: "",
  },
  {
    id: 5,
    first_name: "Bootcamp",
    last_name: "Davomiylik: 6 oy ",
    email: "Darslar soni: 16 ta",
    name: "Muhammad Yunus",
    img: "",
  },
  {
    id: 6,
    first_name: "Kiberxavfsizlik va Raspberry Pi...",
    last_name: "Davomiylik: 6 oy ",
    email: "Darslar soni: 24 ta",
    name: "Muhammad Yunus",
    img: "",
  },
  {
    id: 7,
    first_name: "Flutter",
    last_name: "Davomiylik: 6 oy ",
    email: "Darslar soni: 18 ta",
    name: "Muhammad Yunus",
    img: "",
  },
];

export default data;
